invisible(Sys.setlocale('LC_ALL','English_United States.utf8'))
root<-getwd();base<-dirname(root);source(file.path(base,'KNHANES_HGS_phase2_20260910','core.R'));wc<-function(x,n)write.csv(x,paste0(n,'.csv'),row.names=FALSE,na='',fileEncoding='UTF-8')
profile<-function(d,z,edges){m<-metrics(d,z,edges);w<-d$weight;age<-d$age/10;aslope<-sum(w*(age-weighted.mean(age,w))*(z-weighted.mean(z,w)))/sum(w*(age-weighted.mean(age,w))^2);gr<-cut(d$age,c(20,40,60,80),right=FALSE,labels=c('20-39','40-59','60-79'));ag<-do.call(rbind,lapply(levels(gr),function(g){i<-gr==g;data.frame(age_group=g,N=sum(i),mean_z=weighted.mean(z[i],w[i]),sd_z=wsd(z[i],w[i]),p10=100*weighted.mean(z[i]< -1.282,w[i]),p5=100*weighted.mean(z[i]< -1.645,w[i]))}));s<-m$summary
 out<-data.frame(abs_mean_z=abs(s$mean_z),abs_sd_minus1=abs(s$sd_z-1),abs_age_slope_per10y=abs(aslope),abs_height_slope_per10cm=abs(s$slope_per10cm),abs_p10_minus10_pp=abs(100*s$p10-10),abs_p5_minus5_pp=abs(100*s$p5-5),p10_age_range_pp=diff(range(ag$p10)),p10_height_range_pp=s$p10_range_pp,p5_height_range_pp=s$p5_range_pp)
 list(profile=out,summary=cbind(s,age_slope_per10y=aslope),age=ag,height=m$quintiles)
}

stopifnot(file.exists('Korea_OOF_nine_metrics.csv'));models<-readRDS('frozen_pooled_family_models.rds');hash<-unname(tools::md5sum('frozen_pooled_family_models.rds'))
us<-readRDS(file.path(base,'HGS_pilot_20260908','harmonized_raw_qc.rds'));us$height_m<-us$height/100;us$height10<-us$height/10
pars<-list()
for(s in c('Female','Male'))for(fam in c('NO','BCCG','BCT')){d<-subset(us,eligible&cycle=='G'&sex==s);p<-score_model(models[[paste(s,fam,sep='_')]],d);stopifnot(!any(p$clipped));pars[[paste(s,fam)]]<-data.frame(sex=s,family=fam,N_adaptation=nrow(d),center=weighted.mean(p$z,d$weight),scale=wsd(p$z,d$weight))}
pa<-do.call(rbind,pars);wc(pa,'US_adaptation_parameters');saveRDS(pa,'frozen_US_adaptation.rds');ah<-unname(tools::md5sum('frozen_US_adaptation.rds'))
cutpoints<-read.csv(file.path(base,'US_BCT_recalibration_ladder_20260910','heldout_height_cutpoints.csv'));out<-list();raw<-list();age<-list();height<-list();scores<-list()
for(s in c('Female','Male'))for(fam in c('NO','BCCG','BCT')){
 d<-subset(us,eligible&cycle=='H'&sex==s);a<-subset(pa,sex==s&family==fam);p<-score_model(models[[paste(s,fam,sep='_')]],d);stopifnot(!any(p$clipped));z<-(p$z-a$center)/a$scale;m<-profile(d,z,subset(cutpoints,sex==s)$height);meta<-data.frame(sex=s,family=fam,N=nrow(d));key<-paste(s,fam)
 out[[key]]<-cbind(meta,m$profile);raw[[key]]<-cbind(meta,m$summary);age[[key]]<-cbind(meta,m$age);height[[key]]<-cbind(meta,m$height);scores[[key]]<-data.frame(SEQN=d$SEQN,sex=s,family=fam,z=z)
 if(fam=='BCT'){old<-readRDS(file.path(base,'US_BCT_recalibration_ladder_20260910','heldout_scores.rds'));old<-subset(old,sex==s&method=='Location_scale');stopifnot(max(abs(z-old$z[match(d$SEQN,old$SEQN)]))<1e-12)}
}
ss<-do.call(rbind,out);wc(ss,'US_heldout_nine_metrics');wc(do.call(rbind,raw),'US_heldout_raw_diagnostics');wc(do.call(rbind,age),'US_heldout_age_groups');wc(do.call(rbind,height),'US_heldout_height_groups');saveRDS(do.call(rbind,scores),'US_heldout_scores.rds')
stopifnot(hash==unname(tools::md5sum('frozen_pooled_family_models.rds')),ah==unname(tools::md5sum('frozen_US_adaptation.rds')),nrow(ss)==6,sum(ss$N[ss$family=='BCT'])==4898)
kr<-read.csv('Korea_OOF_nine_metrics.csv');both<-rbind(cbind(setting='Korea OOF',kr),cbind(setting='US held-out',ss[,names(kr)]));wc(both,'family_performance_profile')
met<-names(kr)[-(1:2)];l<-do.call(rbind,lapply(met,function(nm)data.frame(both[,c('setting','sex','family')],metric=nm,value=both[[nm]])));l$metric<-factor(l$metric,levels=met);mx<-tapply(l$value,l$metric,max);l$intensity<-l$value/as.numeric(mx[as.character(l$metric)]);l$label<-ifelse(l$metric %in% met[1:4],sprintf('%.3f',l$value),sprintf('%.2f',l$value));l$row<-paste(l$setting,l$family,sep=' | ');l$row<-factor(l$row,levels=rev(c(paste('Korea OOF',c('NO','BCCG','BCT'),sep=' | '),paste('US held-out',c('NO','BCCG','BCT'),sep=' | '))))
p<-ggplot(l,aes(metric,row,fill=intensity))+geom_tile(color='white')+geom_text(aes(label=label,color=intensity>.58),size=3.6,show.legend=FALSE)+scale_color_manual(values=c('FALSE'='#172A3A','TRUE'='white'))+scale_fill_gradient(low='#F2F6FA',high='#125384',name='Within-metric\nrelative magnitude')+scale_x_discrete(labels=c('|mean Z|','|SD-1|','|age slope|\nper 10y','|height slope|\nper 10cm','|P10-10%|\npp','|P5-5%|\npp','P10 age\nrange pp','P10 height\nrange pp','P5 height\nrange pp'),position='top')+facet_wrap(~sex,ncol=1)+theme_minimal(base_size=11)+theme(panel.grid=element_blank(),axis.title=element_blank(),plot.caption=element_text(hjust=0))+labs(title='Fixed-structure distribution-family sensitivity',subtitle='Same Korean PSU folds; model-specific US location + scale adaptation only; BCT remains locked primary',caption='Korea: 2014-2019, two repeats of five-fold PSU CV. US: adaptation 2011-2012, held-out 2013-2014.\nAbsolute deviations / ranges; smaller is closer to target. Color scaled separately by metric, not a composite score.\nAll methods use identical age/height basis dimensions; distribution-specific scale parameters have different interpretations.')
ggsave('family_performance_profile.png',p,width=16,height=8,dpi=200,bg='white');ggsave('family_performance_profile.pdf',p,width=16,height=8,bg='white')
wc(data.frame(check=c('Same 32311 Korean participants and common 2x5 PSU assignment','60 training folds valid; training-only spline knots and parameters','Full-source BCT unchanged from locked pooled primary','US adaptation only 2011-2012','Same 4898 held-out US participants and height cutpoints','BCT held-out scores reproduce original ladder within 1e-12','Korean model and adaptation hashes unchanged'),pass=TRUE),'comparison_integrity_checks')
print(ss,row.names=FALSE);cat('US FAMILY COMPARISON COMPLETE\n')